on:
  push:
    tags: 
      - v[0-9].[0-9]+.[0-9]+

env:
  ###################################
  #               API               #
  ###################################
  DEV_A_API: "env-dev-a-api-helixpay"
  DEV_B_API: "env-dev-b-api-helixpay"
  DEV_C_API: "env-dev-c-api-helixpay"
  STAGING_A_API: "env-staging-a-api-helixpay"
  STAGING_B_API: "env-staging-b-api-helixpay"
  STAGING_C_API: "env-staging-c-api-helixpay"
  STAGING_API: "env-staging-api-helixpay"
  SANDBOX_API: "helixpay-sandbox-api"
  PROD_API: "helixpay-production-api"

  ###################################
  #             WORKER              #
  ###################################
  DEV_A_WORKER: "env-dev-a-worker-helixpay"
  DEV_B_WORKER: "env-dev-b-worker-helixpay"
  DEV_C_WORKER: "env-dev-c-worker-helixpay"
  STAGING_A_WORKER: "env-staging-a-worker-helixpay"
  STAGING_B_WORKER: "env-staging-b-worker-helixpay"
  STAGING_C_WORKER: "env-staging-c-worker-helixpay"
  STAGING_WORKER: "env-staging-worker-helixpay"
  SANDBOX_WORKER: "helixpay-sandbox-worker"
  PROD_WORKER: "helixpay-production-worker"

  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write
  contents: read

jobs:

################################################################################################################
#                                                     API                                                      #
################################################################################################################

  production-api-build:
    runs-on: self-hosted
    container: 
      image: cimg/php:8.1.9-node
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Get API
        run: |
          echo "${{ secrets.CONFIG_API_PROD }}" > .elasticbeanstalk/config.yml
          echo "${{ secrets.ENV_API_PROD }}" >> .env
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: config_and_env
          path: |
            .env
            .elasticbeanstalk/config.yml
          retention-days: 1
    
  production-api-test:
    runs-on: self-hosted
    needs: [production-api-build]
    container: 
      image: cimg/php:8.1.9-node
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install composer
        run: composer install
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: config_and_env
      - name: Test API
        run: php artisan test

  production-api-deploy:
    runs-on: self-hosted
    needs: [production-api-build, production-api-test]
    container: 
      image: cimg/php:8.1.9-node
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::903706683286:role/helixpay-production-github-role
          role-session-name: Deploy-API
          aws-region: ${{ env.AWS_REGION }}
      - name: Install composer
        run: composer install
      - name: Install CLI
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install awsebcli
          sudo pip3 install awscli
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: config_and_env
      - name: Include wazuh agent production
        run: aws s3 cp s3://helixpay-wazuh-agent .platform/hooks/postdeploy/ --recursive
      - name: Deploy to Elasticbeanstalk
        run: |
          eb use ${{ env.PROD_API }}
          eb list
      #- name: Run seeder
      #  run: aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=tag:Name,Values=${{ env.PROD_API }}" --cli-input-json file://release/migrate_seed.json --comment ${{ env.PROD_API }} --region ${{ env.AWS_REGION }}

################################################################################################################
#                                                     WORKER                                                   #
################################################################################################################

  production-worker-build:
      runs-on: self-hosted
      needs: [production-api-build]
      container: 
        image: cimg/php:8.1.9-node
        options: --user root
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name: Get API
          run: |
            echo "${{ secrets.CONFIG_WORKER_PROD }}" > .elasticbeanstalk/config.yml
            echo "${{ secrets.ENV_WORKER_PROD }}" >> .env
        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: config_and_api
            path: |
              .env
              .elasticbeanstalk/config.yml
            retention-days: 1

  production-worker-deploy:
    runs-on: self-hosted
    needs: [production-worker-build]
    container: 
      image: cimg/php:8.1.9-node
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::903706683286:role/helixpay-production-github-role
          role-session-name: Deploy-API-Production
          aws-region: ap-southeast-1
      - name: Install composer
        run: composer install
      - name: Install CLI
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install awsebcli
          sudo pip3 install awscli
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: config_and_api
      - name: Exclude for worker production
        run: sudo rm -r .ebextensions/03_elb_health_check.config .ebextensions/04_http_to_https.config
      - name: Deploy to Elasticbeanstalk
        run: |
          eb use ${{ env.PROD_WORKER }}
          eb list