
name: API-Main

on:
  push:
    branches: 
      - main

jobs:
  prod-build:
    runs-on: ubuntu-latest
    container: 
      image: cimg/php:8.1.9-node
    steps:
      - name: Setup file system permissions
        run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - run: |
          composer install
          echo "${{ secrets.CONFIG_API_DEV_A }}" >> .elasticbeanstalk/config.yml
          echo "${{ secrets.ENV_API_DEV_A }}" >> .env
          cat .env
          cat .elasticbeanstalk/config.yml
          

 