
name: Sandbox-API

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sandbox_api_build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - name: Get API
        run: |
          echo "${{ secrets.CONFIG_API_DEV_A }}" > .elasticbeanstalk/config.yml
          echo "${{ secrets.ENV_API_DEV_A }}" >> .env
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: config_and_api
          path: |
            .env
            .elasticbeanstalk/config.yml
          retention-days: 1
    
  sandbox_api_test:
    runs-on: ubuntu-latest
    needs: [sandbox_api_build]
    container: 
      image: cimg/php:8.1.9-node
    steps:
      - name: Setup file system permissions
        run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - name: Install composer
        run: composer install
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: config_and_api
      - name: Test API
        run: php artisan test

  sandbox_api_deploy:
    runs-on: ubuntu-latest
    needs: [sandbox_api_build, sandbox_api_test]
    container: 
      image: cimg/php:8.1.9-node
    steps:
      - name: Setup file system permissions
        run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::302489882384:role/helixpay-dev-github-role
            role-session-name: Deploy-API
            aws-region: ap-southeast-1
      - name: Install composer
        run: |
          composer install
      - name: Install CLI
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install awsebcli
          sudo pip3 install awscli
      - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: config_and_api
      - name: Exclude for API
        run: sudo rm -r .ebextensions/10_wazuh.config .platform/hooks/postdeploy/08_chown_storage.sh
      - name: Deploy to Elasticbeanstalk
        run: |
          eb deploy

